# Generated by Django 2.0.1 on 2018-01-13 11:39

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180113_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'Draft'), (100, 'Published')], default=0, protected=True),
        ),
    ]
