# Generated by Django 2.0.1 on 2018-01-13 13:12

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'Draft'), (100, 'Published')], default=0),
        ),
    ]
