# Generated by Django 2.0.1 on 2018-01-13 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180113_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['published_on']},
        ),
    ]
