# Generated by Django 2.0.1 on 2018-01-13 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180113_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_on']},
        ),
    ]
